### ISSUE TITLE
Make seed configurable

### ISSUE THREAD

**Issue by SebastianSchlag** [mayerrn/HYPE#4]
Currently, HYPE always computes the same result for a hypergraph although the algorithm itself is randomized. In order to be able to actively exploit randomization, it would be nice if it were possible to seed HYPE's random generator via a commandline parameter.

**Comment by DarkWingMcQuack** [comment]
Currently HYPE uses the following implementation [here](https://github.com/mayerrn/HYPE/blob/fee022a4e5d8e0f1c5a4a3a39be4d3d71edeb915/src/Hypergraph.cpp#L233)
```
auto part::Hypergraph::getRandomNode() const
    -> uint64_t
{
    return _vertices.begin()->first;
}
```
which grabs the first node from the hashmap. We consider this random and use this kind of implementation because it is considerably faster than extracting real random nodes.

**Comment by SebastianSchlag** [comment]
Unfortunately, this does **not** make your implementation random at all, since most (all?) current c++ compilers use _identity_ as hash function for integer types (see https://en.cppreference.com/w/cpp/utility/hash).

See for example: https://github.com/gcc-mirror/gcc/blob/cf8c140a8b8131b3ab4f500346dc4c004c899163/libstdc%2B%2B-v3/include/bits/functional_hash.h#L113

**Comment by DarkWingMcQuack** [comment]
We just need a next node from where we start again if there is no new candidate found.
[Here](https://github.com/mayerrn/HYPE/blob/fee022a4e5d8e0f1c5a4a3a39be4d3d71edeb915/src/SSet.cpp#L109) you can see that we only use the `getRandomNode` function, to continue building up the partition.
Maybe the name is confusing because it is not realy random.
In the future it could be interesting how to pick this next node and maybe we implement such a functionality. I tested a truly random selection, but it was horribly slow, since getting a random element out of a hashmap was in `O(n)`(at least with the horrible random node selection I implemented). I will have a look and will maybe implement truly random node selection for research purposes.

**Comment by SebastianSchlag** [comment]
> We just need a next node from where we start again if there is no new candidate found.
> [Here](https://github.com/mayerrn/HYPE/blob/fee022a4e5d8e0f1c5a4a3a39be4d3d71edeb915/src/SSet.cpp#L109) you can see that we only use the `getRandomNode` function, to continue building up the partition.
> Maybe the name is confusing because it is not realy random.

As I noted before, it is not random at all. Furthermore, this way you might end up with a single 'poor' choice for the new node _all the time_, since the current implementation will always return the **same** node.

> In the future it could be interesting how to pick this next node and maybe we implement such a functionality. I tested a truly random selection, but it was horribly slow, since getting a random element out of a hashmap was in `O(n)`(at least with the horrible random node selection I implemented). I will have a look and will maybe implement truly random node selection for research purposes.

Sorry, but this seems to be a lame excuse, since it is rather trivial to implement this in a way that takes constant time. ;)

**Comment by DarkWingMcQuack** [comment]
Implemented, but it currently uses `std::advance` to get an iterator to a random element.
This is in fact in O(n). Feel free to optimize this away if you know how to.
